version: "3"
services:
  client:
    image: frans26/fibo-client:latest
    mem_limit: 128m
    hostname: client
  server:
    image: frans26/fibo-server:latest
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: frans26/fibo-worker:latest
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: frans26/fibo-nginx:latest
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80
