name: Deploy multiple containers

on:
  push:
    branches:
      - main

jobs:
  test_client_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test client app
        run: |
          docker build -t frans26/fibo-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true frans26/fibo-test npm run test -- --coverage
  client_build_push:
    runs-on: ubuntu-latest
    needs: [test_client_app]
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build and push client
          uses: docker/build-push-action@v4
          with:
            context: ./client
            push: true
            tags: frans26/fibo-client:latest
        - name: Build and push nginx
          uses: docker/build-push-action@v4
          with:
            context: ./nginx
            push: true
            tags: frans26/fibo-nginx:latest
        - name: Build and push server
          uses: docker/build-push-action@v4
          with:
            context: ./server
            push: true
            tags: frans26/fibo-server:latest
        - name: Build and push worker
          uses: docker/build-push-action@v4
          with:
            context: ./worker
            push: true
            tags: frans26/fibo-worker:latest
        - name: Generate deployment package
          run: zip -r deploy.zip . -x '*.git*'
        - name: Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: fibo-docker
            environment_name: Fibodocker-env
            existing_bucket_name: elasticbeanstalk-ap-southeast-1-594092054201
            region: ap-southeast-1
            version_label: ${{ github.sha }}
            deployment_package: deploy.zip